apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-node-holla
spec:
  replicas: 5
  selector:
    matchLabels:
      app: k8s-node-holla
  template:
    metadata:
      labels:
        app: k8s-node-holla
    spec:
      containers:
        - name: k8s-node-holla
          image: kushwahaashish/k8s-node-holla
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 8790
