apiVersion: v1
kind: Service
metadata:
  name: k8s-node-nginx
spec:
  type: LoadBalancer
  selector:
    app: k8s-node-nginx
  ports:
    - port: 3333
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-node-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-node-nginx
  template:
    metadata:
      labels:
        app: k8s-node-nginx
    spec:
      containers:
        - name: k8s-node-nginx
          image: kushwahaashish/k8s-node-nginxf
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 8790
